# Current docker latest stable version
version: '3'

# List of services that are going to be installed once it is run
services:
  # nodejs service for the main app
  nodejs:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
      - "9229:9229"
    # Keeps refreshing changes happen inside src dir
    volumes:
      - './src:/var/www/html'
    # Environment vars for the App
    env_file:
      - .env
    # Restart the server if it's crashing
    restart: always
    depends_on:
      - postgres
    container_name: 'nodejs'
  # postgres service for db
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    container_name: 'postgres'